apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace:  default-mem-example
spec:
  limits:
  - default:
      memory: 50Mi
      cpu: 1
    defaultRequest:
      memory: 25Mi
      cpu: 0.5
    max:
      memory: 256Mi
    min:
      memory: 25Mi
    type: Container